services:
  - type: web
    name: bouldering-elo-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bouldering-elo-db
          property: connectionString

databases:
  - name: bouldering-elo-db
    databaseName: boulderingelo
    user: boulderingelo
    plan: free
    region: oregon
